language: python

python:
  - "3.6"
  
before_install:
  - sudo apt-get install -y -q mpich libmpich-dev
  
install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
  - cd bingocpp && ./build.sh && cd ..
  
before_script:
  - export PYTHONPATH=$PYTHONPATH:$PWD
  
script:
  - pytest tests --cov=bingo

after_script:
  - coveralls
